### ISSUE TITLE
Support for restore-keys

### ISSUE THREAD

**Issue by JasonEleventeen** [corca-ai/local-cache#23]
Any support for the restore-keys from actions/cache@v3 for cache fallback?

```
      - uses: actions/cache@v3
        name: Composer Cache
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
```
